# Generated by Django 2.2.17 on 2021-01-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startCity', models.TextField()),
                ('pathWeight', models.IntegerField()),
                ('path', models.TextField()),
            ],
        ),
    ]
